config/routes.rb
Rails.application.routes.draw do
  root 'conversions#index'

  resources :conversions, only: [:index] do
    collection do
      post :convert
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/currency.rb
class Currency
  include ActiveModel::Model

  attr_accessor :amount, :currency

  class << self
    def conversion_scale
      {
        USD:  { sub_unit: 'CENT',  multiple: 10 },
        INR:  { sub_unit: 'PAISA', multiple: 10 },
        EURO: { sub_unit: 'CENT',  multiple: 10 },
        JPY:  { sub_unit: 'SEN',   multiple: 10 },
        GBP:  { sub_unit: 'PENCE', multiple: 10 },
        AUD:  { sub_unit: 'CENT',  multiple: 10 },
        CHF:  { sub_unit: 'RAPPN', multiple: 10 }
      }.with_indifferent_access
    end

    def available_currencies
      [
        ['United States Dollar', 'USD'],
        ['Indian Rupee',         'INR'],
        ['European Union EURO',  'EURO'],
        ['Japanese Yen',         'JPY'],
        ['Great British Pound',  'GBP'],
        ['Australian Dollar',    'AUD'],
        ['Swiss Franc',          'CHF']
      ]
    end

    def convert_amount(params)
      scale = conversion_scale[params[:currency]]
      result = (params[:amount].to_f * scale[:multiple])
      "#{result} #{scale[:sub_unit]}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
end

app/controllers/conversions_controller.rb
class ConversionsController < ApplicationController
  def index; end

  def convert
    @conversion = Currency.convert_amount(conversion_params)

    respond_to do |format|
      format.js
    end
  end

  private

  def conversion_params
    params.permit(:amount, :currency)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversions_helper.rb
module ConversionsHelper
end

app/views/conversions/convert.js.erb
$("#result-area").html("Result: <%= @conversion %>")

app/views/conversions/index.html.erb
<fieldset>
  <legend>Currency Conversion</legend>
  <%= form_with model: @currency, url: convert_conversions_path, id: 'currency-form', data: {turbo: 'false', remote: 'true'} do |f| %>
    <div class="field">
      <b><%= f.label :amount %></b> <br/>
      <%= f.number_field :amount, step: :any %>
    </div>

    <br/>
    <br/>

    <div class="field">
      <b><%= f.label :currency %></b> <br/>
      <%= f.select :currency, options_for_select(Currency.available_currencies) %>
    </div>

    <div class="actions">
      <%= f.submit "Submit", id: 'currency-submit' %>
    </div>
  <% end %>

  <br>
  <br>
  <div>
    <b id="result-area"></b>
  </div>
</fieldset>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PeachpayPracticalTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  </body>
</html>